Devel ast
pyccel/GeLaTo pull request #6
Opened 2020-09-03 09:04 UTC by saidctb

2020-09-07 14:38 UTC, yguclu commented
It appears that the Travis CI integration is broken for this repository.

2020-09-14 09:14 UTC, yguclu commented
I have fixed the Travis CI integration. Does this PR depend on the changes in SymPDE given by PR [#71](https://github.com/pyccel/sympde/pull/71)? That information should be added to this PR's description.

2020-09-14 09:36 UTC, saidctb commented
> I have fixed the Travis CI integration. Does this PR depend on the changes in SymPDE given by PR [#71](https://github.com/pyccel/sympde/pull/71)? That information should be added to this PR's description.
yes it depends on them

2020-09-21 14:27 UTC, yguclu requested changes
A very good pull request!
I've noticed some unused imports, please remove them...

2020-09-21 14:27 UTC, yguclu commented on gelato/tests/test_gelatize_3d.py
> +from sympde.topology import dx, dy, dz, dx1, dx2, dx3
`dx, dy, dz` are never used in this module, so they should not be imported.

2020-09-21 14:27 UTC, yguclu commented on gelato/tests/test_gelatize_2d.py
> +from sympde.topology import dx, dy, dz, dx1, dx2, dx3
`dx, dy, dz` are never used in this module, so they should not be imported.

2020-09-21 14:30 UTC, yguclu commented on gelato/tests/test_gelatize_3d.py
> +from sympde.topology import dx, dy, dz, dx1, dx2, dx3
I've done it myself.

2020-09-21 14:31 UTC, yguclu commented on gelato/tests/test_gelatize_2d.py
> +from sympde.topology import dx, dy, dz, dx1, dx2, dx3
I've removed them myself.

2020-09-21 15:00 UTC, yguclu approved these changes

2020-09-21 15:16 UTC, merged